name: Pull Requests

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    permissions:
      contents: read
      pull-requests: write

    uses: ./.github/workflows/call-build-and-test.yml

    secrets: inherit